# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170726_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='email',
            new_name='email_mod',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='name',
            new_name='name_mod',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='password',
            new_name='password_mod',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='username',
            new_name='username_mod',
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SignUpModel'),
        ),
    ]
